### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by farishkash** [sean-one/prj-rev-bwfs-dasmoto#1]
Overall excellent project.

You not only did everything I look for in this first project but you also did one of the best practices I look for in a later project review which is the use of alt text for the images.

Everything is well structured and readable.

The only thing I would point out is 

.sectionContent {

}

If you aren't using any styles it is perfectly acceptable to remove this from the css file and the class from the div.

To prepare you for the upcoming projects go to flexboxfroggy.com and see how far you can get. Flexbox will be used heavily in the later projects.

**Comment by sean-one** [comment]
@farishkash Thank you for your review.  I was going to use that class for something then ended up not doing anything with it and forgot to take it out.  Over all the project was sent with out me taking a second look at it.  I am glad it looks like I am on the right track.  I will check out the link you sent.  Thank you again for your feedback.
